### ISSUE TITLE
 In Asset Repair, the drop-down list for linking the Purchase Invoice is not filtering results based on the entered number. 

### ISSUE THREAD

**Issue by rushabhmaywade** [8848digital/Assets#101]
### Information about bug

![image](https://github.com/user-attachments/assets/d1c42f1f-a1dd-4b96-a851-831a7492aa61)

### Module

assets

### Version

Assets: v0.0.1 (pre-prod)

CRM: v0.0.1 (master)

ERPNext: v15.36.2 (pre-prod)

Frappe Framework: v15.41.0 (pre-prod)

Payments: v0.0.1 (version-15)

Projects: v0.0.1 (master)

sales_commission: v0.0.1 (master)

### Installation method

None

**Comment by tohidmalik002** [comment]
Pr raised: https://github.com/8848digital/Assets/pull/104

**Comment by tinadn** [comment]
Resolved. Hence closing.
