### ISSUE TITLE
Server Error when we "make depreciation entry" on submission of Asset Depreciation Schedule.

### ISSUE THREAD

**Issue by charissa8848** [8848digital/Assets#106]
### Information about bug

When the depreciation schedule is created for an asset, for the previous periods for which depreciation is to be recorded, when we manually "make journal entry'' the system throws a server error-

![Screenshot 2024-12-02 130356](https://github.com/user-attachments/assets/811ce1e1-ec78-4c33-b127-2c91419edba1)

### Module

assets

### Version

Assets: v0.0.1 (pre-prod)

ERPNext: v15.36.2 (pre-prod)

Frappe Framework: v15.41.0 (pre-prod)

### Installation method

None

**Comment by tinadn** [comment]
@charissa8848 accounting dimensions rq jobs were stopped. Now working fine. Hence closing.

**Comment by charissa8848** [comment]
yeah it works fine, thanks Tina!
