### ISSUE TITLE
Unable to create asset

### ISSUE THREAD

**Issue by deepdoshi79** [8848digital/Assets#107]
### Information about bug

Getting Below Error while creating asset
![image](https://github.com/user-attachments/assets/92d30fe7-2482-48cf-b89e-2c98e5ea2e8a)

### Module

assets

### Version

Assets: v0.0.1 (pre-prod)

CRM: v0.0.1 (master)

ERPNext: v15.36.2 (pre-prod)

Frappe Framework: v15.41.0 (pre-prod)

Payments: v0.0.1 (version-15)

Projects: v0.0.1 (master)

sales_commission: v0.0.1 (master)

### Installation method

None

**Comment by tinadn** [comment]
Accounting Dimensions was not created. Now working fine. Hence closing.
