### ISSUE TITLE
The purchase invoice for auto asset creation is generating an asset in draft status but is not retrieving the invoice.

### ISSUE THREAD

**Issue by deepdoshi79** [8848digital/Assets#116]
### Information about bug

![image](https://github.com/user-attachments/assets/b523f4cf-1d5e-4ba6-a3fd-f12de811a12e)
![image](https://github.com/user-attachments/assets/591b2b4f-2bf2-4348-8c2a-6b4738c4ac72)
![image](https://github.com/user-attachments/assets/04bca708-0472-4f24-bc55-fb5cc42f9c23)

### Module

assets

### Version

Assets: v0.0.1 (pre-prod)
CRM: v0.0.1 (master)
ERPNext: v15.46.1 (pre-prod)
Frappe Framework: v15.50.1 (pre-prod)
India Compliance: v15.14.5 (pre-prod)
Payments: v0.0.1 (version-15)
Projects: v0.0.1 (master)
sales_commission: v0.0.1 (master)

### Installation method

None

**Comment by Nandhini8848** [comment]
@deepdoshi79 The issue was with Accounting Dimensions created in the Purchase Invoice Reference Doctype, where it considered all accounting dimensions, both enabled and disabled.

**Comment by deepdoshi79** [comment]
Functionality working after deleting purchase invoice AD
