### ISSUE TITLE
Current Asset Value Not Auto-Populating in Asset Value Adjustment

### ISSUE THREAD

**Issue by deepdoshi79** [8848digital/Assets#26]
### Information about bug

The current asset value is not automatically populating in the asset value adjustment , and an error message appears during submission.
![image](https://github.com/user-attachments/assets/a2d3c0d4-4de8-428c-bb5e-d6ec960e2d9e)
![image](https://github.com/user-attachments/assets/9d205449-a4c0-42a4-908e-d61b6b2316d7)

### Module

assets

### Version

Assets: v0.0.1 (pre-prod)

ERPNext: v15.34.0 (pre-prod)

Frappe Framework: v15.41.0 (pre-prod)

### Installation method

None

**Comment by chintanshah8848** [comment]
current asset value is fetched on selection of Finance book
