### ISSUE TITLE
In the Asset Depreciation Ledger, Asset Depreciations and Balances and Fixed Asset Register Reports  assets, asset categories, and cost centers should be filtered based on the selected company. It shows values of all the companies

### ISSUE THREAD

**Issue by deepdoshi79** [8848digital/Assets#33]
In the Asset Depreciation Ledger, Asset Depreciations and Balances and Fixed Asset Register Reports  assets, asset categories, and cost centers should be filtered based on the selected company. It shows values of all the companies
![image](https://github.com/user-attachments/assets/fe11007a-3f79-495c-8709-e34ebb10daf6)
Reference Ledger
![image](https://github.com/user-attachments/assets/2dc275ff-95e2-4dff-adea-ec530d3f5ef1)

**Comment by manoj8848** [comment]
https://github.com/8848digital/Assets/pull/27
https://github.com/8848digital/Assets/pull/29
https://github.com/8848digital/Assets/pull/30
Completed

**Comment by tohidmalik002** [comment]
Completed Hence Closing
