### ISSUE TITLE
When clicking on "completed" and "canceled" in the Asset Repair list, an error occurs.

### ISSUE THREAD

**Issue by deepdoshi79** [8848digital/Assets#39]
### Information about bug

When clicking on "completed" and "cancelled" in the Asset Repair list, an error occurs. Currently, it only filters by draft status from document status; it should also filter submitted and cancelled based on document status
![image](https://github.com/user-attachments/assets/f4af563f-5a31-4303-bdb2-49f323f10f88)
![image](https://github.com/user-attachments/assets/8671b77f-afc2-49d5-ba79-79f746ea67ec)
![image](https://github.com/user-attachments/assets/6e920ba1-93d5-48ad-8b99-d9ab9dc438a4)

### Module

assets

### Version

Assets: v0.0.1 (pre-prod)

ERPNext: v15.34.0 (pre-prod)

Frappe Framework: v15.41.0 (pre-prod)

### Installation method

None

**Comment by tohidmalik002** [comment]
PR Raised: https://github.com/8848digital/Assets/pull/41

**Comment by tinadn** [comment]
Issue resolved. Hence closing.
