### ISSUE TITLE
When creating an existing or composite asset in asset doctype, the purchase date must be mandatory.

### ISSUE THREAD

**Issue by deepdoshi79** [8848digital/Assets#45]
### Discussed in https://github.com/8848digital/Assets/discussions/44

<div type='discussions-op-text'>

<sup>Originally posted by **deepdoshi79** October 29, 2024</sup>
When creating an existing or composite asset in asset doctype, the purchase date must be mandatory.
![image](https://github.com/user-attachments/assets/84c83e03-aab3-463b-bed2-b95487dc1123)
![image](https://github.com/user-attachments/assets/a27a8cb2-4ce3-4bc9-8925-b228360b0015)
</div>

**Comment by tohidmalik002** [comment]
Done https://github.com/8848digital/Assets/pull/67

**Comment by deepdoshi79** [comment]
Enhancement done. Functionality working. Issue Reolved.
