### ISSUE TITLE
An error occurs when creating a purchase invoice for an asset.

### ISSUE THREAD

**Issue by deepdoshi79** [8848digital/Assets#46]
### Information about bug

When creating a purchase invoice with update stock checkbox, if the item is a fixed asset and the option to create the asset upon purchase is enabled, the following error occurs:
![image](https://github.com/user-attachments/assets/dd2bad96-b8a8-43cc-a21a-ba42acf557d2)

### Module

assets

### Version

Assets: v0.0.1 (pre-prod)

ERPNext: v15.34.0 (pre-prod)

Frappe Framework: v15.41.0 (pre-prod)

### Installation method

None

**Comment by tohidmalik002** [comment]
Fixed https://github.com/8848digital/Assets/pull/49. Please check

**Comment by deepdoshi79** [comment]
issue resolved
