### ISSUE TITLE
The GL entry is displaying zero when creating a purchase receipt for a fixed asset.

### ISSUE THREAD

**Issue by deepdoshi79** [8848digital/Assets#47]
### Information about bug

The GL entry is displaying zero value when creating a purchase receipt for a fixed asset.
![image](https://github.com/user-attachments/assets/29965cd4-6ca2-4bbf-bb57-70b3229d0481)
![image](https://github.com/user-attachments/assets/e78ffa9c-f83a-4e29-9a91-979204fc17e5)

### Module

assets

### Version

Assets: v0.0.1 (pre-prod)

ERPNext: v15.34.0 (pre-prod)

Frappe Framework: v15.41.0 (pre-prod)

### Installation method

None

**Comment by tohidmalik002** [comment]
Fixed https://github.com/8848digital/Assets/pull/49. Please Test
