### ISSUE TITLE
When creating a purchase receipt for a fixed asset, the asset location field is not appearing in the item child table.

### ISSUE THREAD

**Issue by deepdoshi79** [8848digital/Assets#48]
### Information about bug

When creating a purchase receipt for a fixed asset, the asset location field is not appearing in the item child table.
Postgres
![image](https://github.com/user-attachments/assets/61877be6-81d0-4796-9ae7-9af65afc8b3f)
Maria DB
![image](https://github.com/user-attachments/assets/ebf3302f-454a-47f9-b268-b72b5dbe172a)

### Module

assets

### Version

Assets: v0.0.1 (pre-prod)

ERPNext: v15.34.0 (pre-prod)

Frappe Framework: v15.41.0 (pre-prod)

### Installation method

None

**Comment by tohidmalik002** [comment]
Working Now
![Screenshot 2024-10-31 150315](https://github.com/user-attachments/assets/14c4c2f9-0564-4269-9172-3dc4270aceb7)

**Comment by deepdoshi79** [comment]
Issue Resolved
