### ISSUE TITLE
The asset location is not being fetched in asset when creating a purchase receipt for a fixed asset item, for auto-creation of the asset on purchase is enabled.

### ISSUE THREAD

**Issue by deepdoshi79** [8848digital/Assets#54]
### Information about bug

The asset location is not being fetched in asset when creating a purchase receipt for a fixed asset item, for auto-creation of the asset on purchase is enabled.
![image](https://github.com/user-attachments/assets/9cf7a421-e543-4d8d-aa14-78e84d72d3c2)
![image](https://github.com/user-attachments/assets/6c003344-4903-41be-bc48-2f388d477190)

### Module

assets

### Version

Assets: v0.0.1 (pre-prod)

ERPNext: v15.34.0 (pre-prod)

Frappe Framework: v15.41.0 (pre-prod)

### Installation method

None

**Comment by rahulgupta8848** [comment]
pr raise: https://github.com/8848digital/erpnext/pull/511

**Comment by tinadn** [comment]
Issue Resolved. Hence closing.
