### ISSUE TITLE
The purchase invoice allows the submission of entries for fixed assets without an asset location.

### ISSUE THREAD

**Issue by deepdoshi79** [8848digital/Assets#60]
### Information about bug

The purchase invoice allows the submission of entries for fixed assets without an asset location.
![image](https://github.com/user-attachments/assets/f260fd79-ca50-498d-a248-00674168a0d6)
![image](https://github.com/user-attachments/assets/f8cd75cf-5da7-4819-a6ca-44c65500c3a9)

### Module

assets

### Version

Assets: v0.0.1 (pre-prod)

ERPNext: v15.34.0 (pre-prod)

Frappe Framework: v15.41.0 (pre-prod)

### Installation method

None

**Comment by tohidmalik002** [comment]
As per discussion with yatish. This is not a bug and this enhancement is not required. Hence we can close this.

**Comment by deepdoshi79** [comment]
This is the Functionality of the Asset on Purchase Hence Issue is Resolved
