### ISSUE TITLE
When performing manual depreciation, the system is fetching the session's default cost center in the accumulated depreciation account while creating depreciation journal entry

### ISSUE THREAD

**Issue by deepdoshi79** [8848digital/Assets#61]
### Information about bug

When performing manual depreciation, the system is fetching the session's default cost center in the accumulated depreciation account while creating depreciation journal entry
![image](https://github.com/user-attachments/assets/988e6b7f-74c7-435d-a76a-873abb50a84d)
![image](https://github.com/user-attachments/assets/1037212c-0204-4002-87ae-60ec10824e9a)
![image](https://github.com/user-attachments/assets/5e46f80a-f87f-4397-94b7-634d1613ba89)

### Module

assets

### Version

Assets: v0.0.1 (pre-prod)

ERPNext: v15.34.0 (pre-prod)

Frappe Framework: v15.41.0 (pre-prod)

### Installation method

None

**Comment by tohidmalik002** [comment]
Done https://github.com/8848digital/Assets/pull/67

**Comment by deepdoshi79** [comment]
Functionality Working. Issue Resolved.
