### ISSUE TITLE
When selecting consumed stock during asset capitalization, the updated stock balance is not reflecting in the stock summary report or the item master dashboard.

### ISSUE THREAD

**Issue by deepdoshi79** [8848digital/Assets#63]
### Information about bug

When selecting consumed stock during asset capitalization, the updated stock balance is not reflecting in the stock summary report or and the item master dashboard.
![image](https://github.com/user-attachments/assets/18f332f3-6660-4edd-bc7d-72fe32eaa05f)
![image](https://github.com/user-attachments/assets/19973212-87ef-45db-af33-f48152783b59)
![image](https://github.com/user-attachments/assets/d1a40163-5af3-4330-ba0d-642eb44ca7cf)
![image](https://github.com/user-attachments/assets/0fcda30c-0b10-44aa-a83d-a59eb3c2fb23)

### Module

assets

### Version

Assets: v0.0.1 (pre-prod)

ERPNext: v15.34.0 (pre-prod)

Frappe Framework: v15.41.0 (pre-prod)

### Installation method

None

**Comment by tohidmalik002** [comment]
There is "Do reposting for each Stock Transaction" checkbox in Stock Reposting Settings. If you uncheck this stock will decrease in asset capitalization
![Screenshot 2024-11-07 123644](https://github.com/user-attachments/assets/e7ded2e2-67f4-4a49-aaa6-3ae2d2faf7f3)

**Comment by deepdoshi79** [comment]
Functionality working after  unchecking "Do reposting for each Stock Transaction"
Issue Resolved
