### ISSUE TITLE
In the asset movement doctype, when the purpose is selected as "Issue," it is automatically fetching the target location.

### ISSUE THREAD

**Issue by deepdoshi79** [8848digital/Assets#65]
### Information about bug

In the asset movement doctype, when the purpose is selected as "Issue," it is automatically fetching the target location.
![image](https://github.com/user-attachments/assets/51067f6c-8601-4dbd-9c5d-3a2cbfb17a23)
![image](https://github.com/user-attachments/assets/13eb4eba-2e2b-4931-8080-39d05c6e3e14)

### Module

assets

### Version

Assets: v0.0.1 (pre-prod)

ERPNext: v15.34.0 (pre-prod)

Frappe Framework: v15.41.0 (pre-prod)

### Installation method

None

**Comment by tohidmalik002** [comment]
Fixed https://github.com/8848digital/Assets/pull/66

**Comment by deepdoshi79** [comment]
Functionality Working Issue Resolved
