### ISSUE TITLE
The Finance Book should be considered mandatory when calculating depreciation during asset submission.

### ISSUE THREAD

**Issue by deepdoshi79** [8848digital/Assets#74]
### Information about bug

The Finance Book should be considered mandatory when calculating depreciation during asset submission.
![image](https://github.com/user-attachments/assets/218ee346-8f2d-4bc4-b399-faf468c958f5)

### Module

assets

### Version

Assets: v0.0.1 (pre-prod)

ERPNext: v15.34.0 (pre-prod)

Frappe Framework: v15.41.0 (pre-prod)

### Installation method

None

**Comment by tinadn** [comment]
Resolved. Hence closing.
