### ISSUE TITLE
The asset status is not being updated to "Sold" in the asset list view after the asset is sold.

### ISSUE THREAD

**Issue by deepdoshi79** [8848digital/Assets#76]
### Information about bug

When a sales invoice is generated for an asset, its status is not updated to "Sold" in the asset list view.
![image](https://github.com/user-attachments/assets/664b141d-fdce-40a8-830e-ca982ad6213a)
![image](https://github.com/user-attachments/assets/7ada4d41-ec64-446d-a466-a41aab6d44ff)

Reference From MariaDB
![image](https://github.com/user-attachments/assets/13d8e35e-5130-484b-96ff-55577cc9a6f2)
![image](https://github.com/user-attachments/assets/809cbbb0-1e77-4d2e-9dbe-ec622e7eb085)

### Module

assets

### Version

Assets: v0.0.1 (pre-prod)

ERPNext: v15.34.0 (pre-prod)

Frappe Framework: v15.41.0 (pre-prod)

### Installation method

None

**Comment by sibikumarkuppusamy** [comment]
![image](https://github.com/user-attachments/assets/34592ca8-8760-470e-b404-5dd483636d86)
![image](https://github.com/user-attachments/assets/bde2710a-e239-4878-b617-51c37892bcae)
It's Working fine now.

**Comment by deepdoshi79** [comment]
Functionality Working. Issue Resolved
