### ISSUE TITLE
Asset item creation bug

### ISSUE THREAD

**Issue by MohitJ640** [8848digital/Assets#91]
### Information about bug

![image](https://github.com/user-attachments/assets/c6f137d1-0682-4890-994f-9cfc79aab8a1)

While creating an asset item, I am not getting the columns of "Create grouped asset", "Asset category" & "Asset naming series".

On saving it gives a missing field popup like this:
![image](https://github.com/user-attachments/assets/c69e67d6-d2dd-4880-aede-fa0b105a7c3f)

### Module

assets

### Version

Frappe Framework: v15.41.0 (pre-prod)
ERPNext: v15.35.1 (pre-prod)
Assets: v0.0.1 (pre-prod)

### Installation method

None

**Comment by sibikumarkuppusamy** [comment]
Now it's working Fine
![image](https://github.com/user-attachments/assets/eede207f-c79b-44bd-8ae7-b519a9226dbb)
