### ISSUE TITLE
"Is Fixed Asset" checkbox is missing while creating a new fixed asset as an item

### ISSUE THREAD

**Issue by charissa8848** [8848digital/Assets#95]
### Information about bug

The checkbox for "Is fixed asset" does not appear while creating a new fixed asset as an item . 
![image](https://github.com/user-attachments/assets/0c2d2169-6e8e-41cc-9187-a86eaf62ccdb)

On enabling this option- we should be able to view two more fields 
            a) Checkbox for auto create asset on purchase
            b) Asset Category (to be a mandatory field)

![image](https://github.com/user-attachments/assets/a69bb776-60e0-423c-b48f-521e1d4dc52a)

### Module

assets

### Version

Frappe version: v15.41.0 (pre-prod)

ERPNext Version : v15.35.1 (pre-prod)

Assets: v0.0.1 (pre-prod)

### Installation method

None

**Comment by Abhishek8848** [comment]
It's working now.
![image](https://github.com/user-attachments/assets/15b07bc9-6eb9-4860-bc71-6940b83c80a8)

**Comment by tinadn** [comment]
Working fine. Hence closing.
