### ISSUE TITLE
Once the item has been created with "Is Fixed Asset" option enabled, then on saving the item, the option should be locked and the user should not be able to disable/re-enable it.

### ISSUE THREAD

**Issue by charissa8848** [8848digital/Assets#96]
### Information about bug

Once the item has been created with "Is Fixed Asset" option enabled, then on saving the item, the option (Is Fixed Asset) should be locked and the  user should not be able to disable/re-enable it.

![image](https://github.com/user-attachments/assets/26a37695-315b-420a-8f6a-8aaa92713c35)

### Module

assets

### Version

Frappe Framework: v15.41.0 (pre-prod)

ERPNext: v15.36.2 (pre-prod)

Assets: v0.0.1 (pre-prod)

### Installation method

None

**Comment by tinadn** [comment]
resolved. Hence closing.
