### ISSUE TITLE
The "Asset Location" field is missing while creating a Purchase Receipt for the auto-creation of an asset.

### ISSUE THREAD

**Issue by rushabhmaywade** [8848digital/Assets#99]
### Information about bug

![image](https://github.com/user-attachments/assets/e93d3f94-137c-4432-a2a5-7a16cd22526e)

### Module

assets

### Version

Assets: v0.0.1 (pre-prod)

CRM: v0.0.1 (master)

ERPNext: v15.36.2 (pre-prod)

Frappe Framework: v15.41.0 (pre-prod)

Payments: v0.0.1 (version-15)

Projects: v0.0.1 (master)

sales_commission: v0.0.1 (master)

### Installation method

None

**Comment by deepdoshi79** [comment]
Manufacture tab break in item child table has Asset Location field
